package com.p3program.laugin_project_planner.users;

import jakarta.persistence.*;

/**
 * ---------------- GENERAL LOGIN LOGIC ---------------
 * -    /login form is filled with username and password and a POST
 *      request is sent.
 * -    Credentials are picked up and wrapped into a token safely.
 * -    Token is handled by an AuthenticationManager, sending it to
 *      the AuthenticationProvider.
 * -    Now the database gets involved. Different interfaces holding
 *      methods for fetching the users data is invoked. They compare
 *      the credentials from the token with the database table provided.
 * -    If authentication is succesful, spring updates the SecurityContext
 *      holding the session info, basically remembering if the user is an
 *      ADMIN, throughout the rest of the session, giving access and denying
 *      where ever this might be applicable.
 * -    Finally the users specific url is checked (eg. /kpi), else a default
 *      path is selected upon login
 * -----------------------------------------------------
 * This is where the user is stored in the database and holds the
 * fields, getters and setters that spring.secutity needs to throw
 * data around.
 * Getters and setters are probably autogenerated, some might be redundant
 * or even unsafe.
 */

@Entity
@Table(name = "appuser")
public class AppUser {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String username;
    private String password;
    private String role;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}